routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MessageController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [MessageController::class,'create']);
Route::apiResource('messages', MessageController::class);

app/Models/Message.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Message extends Model
{
    use HasFactory;

    protected $fillable = ['firstName','lastName','email','phone','message','subject'];
    protected $hidden = ['updated_at'];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/MessageController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\MessageRequest;
use App\Http\Resources\MessageResource;
use App\Models\Message;
use App\Models\User;
use App\Notifications\MessageSent;
use Illuminate\Http\Request;

class MessageController extends Controller
{

    public function index()
    {
        //
        return MessageResource::collection(Message::all());
    }


    public function create()
    {
        //
        return view('contact');
    }


    public function store(MessageRequest $request)
    {
        //
        $message = Message::create([
            'firstName' => $request->firstName,
            'lastName' => $request->lastName,
            'email' => $request->email,
            'phone' => $request->phone,
            'subject' => $request->subject,
            'message' => $request->message
        ]);

        //send notification
        $notification = [
            'id' => $message->id,
            'body' => "You have received a message from the Liquid Fish Test Contact Page"
        ];

        $user = User::first();
        $user->notify(new MessageSent($notification));

        return new MessageResource($message);
    }


    public function show(Message $message)
    {
        //
        return view('message',$message);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Message  $message
     * @return \Illuminate\Http\Response
     */
    public function edit(Message $message)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Message  $message
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Message $message)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Message  $message
     * @return \Illuminate\Http\Response
     */
    public function destroy(Message $message)
    {
        //
    }
}

resources/views/contact.blade.php
@extends('layouts.layout')
@section('form')
    <div class="row">
        <div class="col"><strong>Send us a message</strong></div>
        <form class="form-content" id="form" role="form">
            <div class="row">
                <div class="col-lg-6">
                    <div class="form-group">
                        <label for="first-name">First name</label>
                        <input type="text" id="first-name" name="firstName" class="form-control" required>
                    </div><br />
                    <div class="form-group">
                        <label for="email">Email</label>
                        <input type="email" id="email" name="email" class="form-control" required>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="form-group">
                        <label for="last-name">Last name</label>
                        <input type="text" id="last-name" name="lastName" class="form-control" required>
                    </div><br />
                    <div class="form-group">
                        <div class="d-flex justify-content-between">
                            <label for="phone">Phone </label>
                            <span class="help-block">Optional</span>
                        </div>
                        <input type="tel" id="phone" name="phone" class="form-control">
                    </div>
                </div>
            </div>
            <div class="space"></div>
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        <label for="subject">Subject</label>
                        <input type="text" id="subject" name="subject" class="form-control" required>
                    </div><br />
                    <div class="form-group">
                        <div class="d-flex justify-content-between">
                            <label for="message">Message </label>
                            <span class="help-block">Max: 500 Characters</span>
                        </div>

                        <textarea name="message" id="message" class="form-control" maxlength="500" rows="5" required></textarea>
                    </div>
                </div>
            </div>
            <div class="space"></div>
            <div class="row d-flex justify-content-end">
                <div class="spinner-border text-primary" id="spinner"  role="status">
                    <span class="visually-hidden">Loading...</span>
                </div>
                <button type="submit" class="col-sm col-xs-12 col-sm-12 col-md-12 col-lg-1 btn btn-primary submit">Submit</button>
            </div>
        </form>

    </div>
@endsection

@section('info')
    <div class="row">
        <div class="col-12">
            <strong class="white">Contact Information</strong>
            <ul>
                <li><i class="bi-telephone"></i> +1 (555) 123-4567</li>
                <li><i class="bi-envelope"></i> support@liquidfish.com</li>
            </ul>

            <div class="row">
                <div class="col-6">
                    <div class="row">
                        <div class="col-4"><i class="fab fa-facebook-square fa-lg"></i></div>
                        <div class="col-4"><i class="fab fa-github fa-lg"></i></div>
                        <div class="col-4"><i class="fab fa-twitter fa-lg"></i></div>
                    </div>
                </div>
            </div>

        </div>
    </div>
@endsection

resources/views/layouts/layout.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>LIQUID FISH DEVELOPER TEST</title>
    <link rel="icon" href="{{asset('fav.png')}}" >
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <script src = "https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <link href="{{asset('assets/css/custom.css')}}" rel="stylesheet">
    <meta name="csrf-token" content="{{ csrf_token() }}" />
</head>
<body>
<div class="toast-container position-absolute p-3 bottom-0 end-0" id="toastPlacement">
    <div class="toast success-toast align-items-center text-white bg-success border-0" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="d-flex">
            <div class="toast-body" id="response"></div>
            <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
        </div>
    </div>
    <div class="toast error-toast align-items-center text-white bg-danger border-0" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="d-flex">
            <div class="toast-body" id="error"></div>
            <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
        </div>
    </div>
</div>


<div class="container-sm mx-auto" >
    <div class="row main">
        <div class="col-sm col-xs-12 col-sm-12 col-md-12 col-lg-3 sidebar">
            @yield('info')
        </div>
        <div class="col content">
            @yield('form')
        </div>

    </div>
</div>
<script type="text/javascript">
    //Send Message for posting
    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
    });

    $(".submit").click((e) => {
        e.preventDefault();
        document.getElementById('spinner').style.display = 'inline';
        const data = {
            firstName: $("input[name=firstName]").val(),
            lastName: $("input[name=lastName]").val(),
            email: $("input[name=email]").val(),
            phone: $("input[name=phone]").val(),
            subject: $("input[name=subject]").val(),
            message: $("textarea[name=message]").val()
        }

        $.ajax({
            type:'POST',
            url:'{{route('messages.store')}}',
            data,
            success:(response) => {
                document.getElementById('response').innerText = response.data.firstName + "'s message has been successfully sent"
                $('.success-toast').toast('show');
                document.getElementById('spinner').style.display = 'none';
                //reset form
                document.getElementById("form").reset();

            },
            error: (xhr, status, error) => {
                document.getElementById('spinner').style.display = 'none';
                if(xhr.responseJSON.message)
                    document.getElementById('error').innerText = xhr.responseJSON.message
                if(xhr.responseJSON.errors)
                    for (detail in xhr.responseJSON.errors) {
                        document.getElementById('error').innerText = xhr.responseJSON.errors[detail];
                        $('.error-toast').toast('show');

                    }

            }

        });

    });

</script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

resources/views/message.blade.php
@extends('layouts.layout')
@section('form')
    <div class="row">
        <div class="col">
            <table class="table">
                <tbody>
                <tr>
                    <th scope="row">Full Name</th>
                    <td>{{ $firstName . ' '. $lastName  }}</td>

                </tr>
                <tr>
                    <th scope="row">Email</th>
                    <td>{{ $email  }}</td>

                </tr>
                <tr>
                    <th scope="row">Phone</th>
                    <td>{{  $phone ? :'N/A'  }}</td>

                </tr>
                <tr>
                    <th scope="row">Subject</th>
                    <td>{{ $subject  }}</td>
                </tr>

                <tr>
                    <td colspan="2">
                        <b>Message: </b><div class="space"></div>
                        <code> {{ $message  }}</code>
                    </td>
                </tr>
                <tr>
                    <th scope="row">Sent At</th>
                    <td>{{ date('d D, M Y H:i', strtotime($created_at)) }}</td>
                </tr>
                </tbody>
            </table>
            <div class="space"></div>
            <div class="d-flex justify-content-end">
                <a class="btn btn-secondary btn-sm" href="{{ url('/') }}"> <i class="fas fa-arrow-left"></i> Back to Main Contact Page</a>
            </div>

        </div>

    </div>
@endsection

@section('info')
    <div class="row">
        <div class="col-12">
            <strong class="white">Contact Information</strong>
            <ul>
                <li><i class="bi-telephone"></i> +1 (555) 123-4567</li>
                <li><i class="bi-envelope"></i> support@liquidfish.com</li>
            </ul>

            <div class="row">
                <div class="col-6">
                    <div class="row">
                        <div class="col-4"><i class="fab fa-facebook-square fa-lg"></i></div>
                        <div class="col-4"><i class="fab fa-github fa-lg"></i></div>
                        <div class="col-4"><i class="fab fa-twitter fa-lg"></i></div>
                    </div>
                </div>
            </div>

        </div>
    </div>
@endsection